# Neural Networks

## Table of Contents
- [Introduction](#intro)
- [The Neural Network Model](#nn_model)
- [The Dataset](#dataset)
- [Forward Propogation](#forward_prop)

<a id='intro'></a>
### Introduction

...

<a id='nn_model'></a>
### The Neural Network Model

...

<a id='dataset'></a>
### The Dataset

In [1]:
import numpy as np  
import pandas as pd 
import os
import matplotlib.pyplot as plt  
from scipy.io import loadmat  
%matplotlib inline

# load the datasets
data = loadmat('NNdata1.mat')
data2 = loadmat('NNweights.mat')
# X is the feature matrix, y is the vector of class labels
X, y = data['X'], data['y']
# get the intial theta1 and theta2 parameters
theta1, theta2 = data2['Theta1'], data2['Theta2']
print('X dimensions: ', X.shape)
print('y dimensions: ', y.shape)
print('theta1 dimensions: ', theta1.shape)
print('theta2 dimensions: ', theta2.shape)

X dimensions:  (5000, 400)
y dimensions:  (5000, 1)
theta1 dimensions:  (25, 401)
theta2 dimensions:  (10, 26)


In [2]:
# transform each label i from 1,2,...,10 into a 10-dimensional vector with 
# a 1 at the ith index and 0s elsewhere
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(sparse=False)
y_new = enc.fit_transform(y)

for i in range(0, 5000, 500):
    print( 'Label {} is transformed to {}'.format(y[i], y_new[i,:]) )

print('\ny_new dimensions: ', y_new.shape)

Label [10] is transformed to [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
Label [1] is transformed to [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
Label [2] is transformed to [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
Label [3] is transformed to [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
Label [4] is transformed to [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
Label [5] is transformed to [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
Label [6] is transformed to [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
Label [7] is transformed to [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
Label [8] is transformed to [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
Label [9] is transformed to [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]

y_new dimensions:  (5000, 10)


<a id='forward_prop'></a>
### Forward Propogation

In [6]:
def logistic(z):
    
    return 1 / (1 + np.exp(-z))

def forward_propagate(X, theta1, theta2):
    '''
    Implements the forward propogation algorithm.
    Inputs:
    - X is an m by (n+1) numpy array where m = # of training examples
                                           n = # of features
    - theta1 is a p by (m+1) numpy array representing the matrix of
      parameters mapping the input layer to the hidden layer.  
      Note that p = # of units in the hidden layer
    - theta2 is a k by (p+1) numpy array mapping the hidden layer to
      the output layer, where k = # of output units
    '''
    m = X.shape[0]
    # insert column of ones into X
    X = np.insert(X, 0, np.ones(m), axis=1)
    
    # Note:  '@' allows us to multiply numpy arrays like matrices
    Z2 = X @ theta1.T
    A2 = logistic(Z2)
    # insert column of ones into A2
    A2 = np.insert(A2, 0, np.ones(m), axis=1)
    Z3 = A2 @ theta2.T
    
    return X, Z2, A2, Z3, logistic(Z3)

forward_propagate(X, theta1, theta2)

(array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 1.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 1.,  0.,  0., ...,  0.,  0.,  0.]]),
 array([[ -2.93684669,  -2.45058587,   4.95510333, ...,   3.56635593,
           2.81388641,  -2.1195223 ],
        [ -4.81302157,  -2.92257775,   2.6445065 , ...,   2.10497303,
           4.69948787,  -2.76096862],
        [ -4.24056958,  -3.68698052,   5.99656398, ...,   1.54599347,
           3.08971226,  -2.32990819],
        ..., 
        [ -0.86267303,   1.00939507,  -1.67526051, ...,   1.8185898 ,
          -3.18203449,  -1.72539781],
        [  1.74408423,  -0.58216518,  -1.49164167, ...,   4.17481481,
          -0.96739536,  -3.08906563],
        [  3.55683614, -12.11330792,   5.01096205, ...,   7.17585008,
           2.15484114,  -2.9424052 ]]),
 array([[  1.00000000e+00,   5.03618685e-02,   7.9